### ISSUE TITLE
Programmatic access of AWS CDK CLI

### ISSUE THREAD

**Issue by hassankhan** [aws/aws-cdk-rfcs#300]
## Description

Hi there, thanks for creating this package! I was just wondering if there's any way of triggering CDK CLI commands programatically? This would really help with respect to integrating with existing tools and workflows.

[~~RFC 300: Programmatic access of AWS CDK CLI~~](https://github.com/aws/aws-cdk-rfcs/pull/475)

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @hassankhan, @mrgrain 
| Author(s)           | @mrgrain 
| API Bar Raiser      | @rix0rrr 
| Stakeholders        | 

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [x] Community reach out (via Slack and/or Twitter)
- [x] API signed-off (label `api-approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [x] Execution plan submitted (label: `status/planning`)
- [x] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by thenikso** [comment]
I managed to do this following some @ryan-mars suggestions.

```
yarn add aws-cdk
yarn add @aws-cdk/core
# plus all the @aws-cdk/... you need
```

```js
import { App, Stack } from '@aws-cdk/core';
import { SdkProvider } from 'aws-cdk/lib/api/aws-auth';
import { CloudFormationDeployments } from 'aws-cdk/lib/api/cloudformation-deployments';

class ExampleStack extends Stack { /* your stack here */ }

const app = new App();
const stack = new ExampleStack(app, 'StackName', {});

const stackArtifact = app.synth().getStackByName(stack.stackName);

const sdkProvider = await SdkProvider.withAwsCliCompatibleDefaults({
  profile: 'your ~/.aws/config profile name here',
});
const cloudFormation = new CloudFormationDeployments({ sdkProvider });
const deployResultPromise = cloudFormation.deployStack({
  stack: stackArtifact,
});
```

**Comment by iDVB** [comment]
> I managed to do this following some @ryan-mars suggestions.
> 
> 
> 
> ```
> 
> yarn add aws-cdk
> 
> yarn add @aws-cdk/core
> 
> # plus all the @aws-cdk/... you need
> 
> ```
> 
> 
> 
> ```js
> 
> import { App, Stack } from '@aws-cdk/core';
> 
> import { SdkProvider } from 'aws-cdk/lib/api/aws-auth';
> 
> import { CloudFormationDeployments } from 'aws-cdk/lib/api/cloudformation-deployments';
> 
> 
> 
> class ExampleStack extends Stack { /* your stack here */ }
> 
> 
> 
> const app = new App();
> 
> const stack = new ExampleStack(app, 'StackName', {});
> 
> 
> 
> const stackArtifact = app.synth().getStackByName(stack.stackName);
> 
> 
> 
> const sdkProvider = await SdkProvider.withAwsCliCompatibleDefaults({
> 
>   profile: 'your ~/.aws/config profile name here',
> 
> });
> 
> const cloudFormation = new CloudFormationDeployments({ sdkProvider });
> 
> const deployResultPromise = cloudFormation.deployStack({
> 
>   stack: stackArtifact,
> 
> });
> 
> ```

What does the `deployResultPromise` response look like? Is there a way at that point to get the stack resolved outputs?

**Comment by thenikso** [comment]
> What does the `deployResultPromise` response look like? Is there a way at that point to get the stack resolved outputs?

It's an (experimental) [DeployStackResult](https://github.com/aws/aws-cdk/blob/18184df05f5b8478ef9cae1285e45e61a0833822/packages/aws-cdk/lib/api/deploy-stack.ts#L36) when resolved.

I haven't tried to parse it yet, not sure how to use it. Yet I'm guessing the `outputs` map contains everything. Worst case the `stackArn` could be used with the regular SDK to get the stack status

**Comment by iDVB** [comment]
@thenikso noice! Thanks! I've gonna give something a try now.

**Comment by rossng** [comment]
This workaround has been really useful for me. We are [now using it](https://github.com/clowdr-app/clowdr/blob/f6a85a724b136ab94e6a6c020baa5f991cedd12a/services/playout/src/aws/aws.service.ts#L60) to dynamically deploy our MediaLive+MediaPackage+CloudFront stacks at runtime.

To keep things relatively reliable and avoid request timeouts, I don't `await` the result of deployment. Instead I:

* Add an SNS notification topic to each CloudFormation stack and listen for it to complete/fail creation (slightly complicated by CloudFormation's very underspecified event messages!)
* Keep track of deployment jobs that have been started (but not finished) and poll the stack every few minutes to check its status.

I'd love to see this become an officially supported API, since it's much better than the alternatives of using the SDK manually or using traditional CloudFormation configuration files. Hopefully this example code helps anyone else who's trying to do something similar 🙂

**Comment by millionseleshi** [comment]
@rossng thank can for the workaround. is CDK bootstrapping programmatically possible

**Comment by suryatejabandlamudi** [comment]
> ```js
> import { SdkProvider } from 'aws-cdk/lib/api/aws-auth';
> import { CloudFormationDeployments } from 'aws-cdk/lib/api/cloudformation-deployments';
> ...........................
> .............................
> const cloudFormation = new CloudFormationDeployments({ sdkProvider });
> const deployResultPromise = cloudFormation.deployStack({
>   stack: stackArtifact,
> });
> ```



@thenikso   Is there some way I could use python to do a similar deployment?  As most of our codebase is in python. It would be helpful to us if you could point me in the right direction, I could take it from there.

Something like :

> ```py
> from aws_cdk import ( aws_cdk.lib as cloud_formation_deployment )
>  .....
> cloud_formation_deployment.deploy_stack(stack)
> ```

**Comment by codeedog** [comment]
See @thenikso comment of 12 March 2021 for context.

I had to formulate the deploy call as an async call at the module level. This compiled and ran. My particular application requires that I pass in a variable stack name. Although I'm happy to run from a shell, I need to parameterize the name. A programmatic API would be one way to solve this problem.

````
(async () => {
  const synth = app.synth().getStackByName(stack.stackName)
  const sdkProvider = await SdkProvider.withAwsCliCompatibleDefaults({ profile: '<aws profile>' });
  const cloudFormation = new CloudFormationDeployments({ sdkProvider: sdkProvider});
  const deployResultPromise = cloudFormation.deployStack({ stack: synth });
})();
````

I wound up going a different way. Inside my ./bin/platform.ts invocation code, I look for an environment variable and use that instead. Even so, the above code worked well for me at the time.

**Comment by iDVB** [comment]
@thenikso, how did you get [top-level await](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#top-level-await) working in cdk?

**Comment by thenikso** [comment]
as @codeedog noted, you might want to wrap it all in an `async` function

**Comment by pharindoko** [comment]
are there any plans to officially support using only the api functions without the cli  ? This issue is open for 3 years now ...

**Comment by phitoduck** [comment]
+1 for this. My team has been using `troposphere` for a while, and I'm seriously envious of the CDK community. Here are some use cases our team has been using `troposphere` (a Python IaC library) to solve:

1. A custom CLI tool to abstract the hard parts of creating REST APIs. Our data scientists are able to place a `app-config.yml` file in a repository. They then write a FastAPI app compatible with Lambda to serve their models. Then they run `our-custom-cli-tool deploy serverless-rest-api --config app-config.yml`. This is great, because the data scientists don't have to know anything about `troposphere`, `aws-cdk`, or any other IaC tool, but they can easily deploy things.

2. Integration testing: with `troposphere`, we can create a stack--for example, a serverless REST API--and then run tests against it. That could mean sending several requests to a REST API and watching for expected responses. If the tests fail, we tear down the stack. Sure, you can do this with a sequence of CLI calls, or maybe by calling CDK as a subprocess, but it feels clunky.

3. Using stack outputs as inputs to other stacks **at runtime**. Suppose I want to create an IAM user and put those user credentials into the `user-data.sh` script of an AWS Lightsail instance. First, I would create an IAM user stack and save the credentials in AWS Secrets Manager. Then, I would wait for that creation to complete and fetch the credentials. Finally, I would create a stack with an AWS Lightsail instance, rendering the credentials into the `user-data.sh` body.

Conclusion: 

I saw that `pulumi` has an "Automation API" in all the same languages as CDK (they're probably using the `JSII` inspired by AWS CDK, haha). That said, I've really enjoyed the abstraction of CDK and the community support. The other day I created an S3 bucket with the CDK construct. I set the "expire" policy so objects would auto-delete. Then I saw that to achieve that, an entire lambda function had been created to react to "expiry" events and delete the associated objects. That abstraction is so much nicer than anything we've had with `troposphere`!

**Comment by pharindoko** [comment]
Yeah pulumi is on my try-out list.

I made my experience with CDK and it had a benefit for simple small serverless workloads.
For all other things it was just a pain to work with.
In the end it`s just a wrapper for cloudformation and that is the root cause of all nasty IaC problems.

Will use my old good terraform or try out cdktf for real usecases.

**Comment by mnapoli** [comment]
Watch out, programmatic usage of the CDK was strongly impacted in the latest releases: https://github.com/aws/aws-cdk/pull/18667

If you used that approach this is now broken.

**Comment by Tanemahuta** [comment]
Please see: https://github.com/aws/aws-cdk/pull/18667#issuecomment-1075348390

**Comment by Tanemahuta** [comment]
This works: https://github.com/aws/aws-cdk/pull/18667#issuecomment-1075348390

**Comment by fab-mindflow** [comment]
+1.
We also use AWS CDK intensively and programmatically.

**Comment by 3p3r** [comment]
programmatic access to the CLI (or at least its functionality) has been a major pain point at two enterprises I worked for and personally I find it unacceptable to just shell out to the CDK CLI to do *anything*. shelling out is not a secure practice in any environment outside of dev, specifically when people want to integrate with CDK in existing pipelines.

Two *doable* workarounds exist as of today (that I know of):

1. using the stack artifact directly, like I do in `cdk-web`: https://github.com/3p3r/cdk-web/blob/main/cdk-web-cli.js
2. using `cxapi` and reloading the artifacts from disk/memory as mentioned [here](https://github.com/aws/aws-cdk/pull/18667#issuecomment-1075348390)

Unfortunately both approaches rely on `CloudFormationDeployments` class which is an export out of the CLI package. it seems like offering this API directly as an official API is a great place to start working on resolving this RFC.

It is worth noting that using the AWS SDK to "just deploy" the artifacts does not work at all. Complicated stacks require assets, context lookups, and other metadata related tasks to be done normally via the CLI. so that route is almost like duplication of the CLI's source.

Fortunately, my work has been in Node, JS, and TS and I am lucky to have `require` and deep imports in Node. other languages and environments are not that lucky.

**Comment by mnapoli** [comment]
> Unfortunately both approaches rely on CloudFormationDeployments class which is an export out of the CLI package.

That's the problem, this class is no longer usable since https://github.com/aws/aws-cdk/pull/18667

**Comment by 3p3r** [comment]
@mnapoli it is usable in Node still. You need to direct require it outside its deep import. That’s a node core feature. It can’t be taken away. Only import syntax won’t work directly. It will always be possible to require anything until node core stops supporting that.

**Comment by phitoduck** [comment]
@mnapoli Sorry if this is a naive question. What would it take for this feature to move forward? 

- Is this something the community can help with? 
- Are we waiting for a comment on this issue to propose a viable approach? 
- Does it have to do with the prioritization of the internal AWS CDK team?
- Do you suspect that it may _never_ happen due to a fundamental conflict with how CDK is architected? 

I feel like this is potentially such an amazing feature that would close a large gap between what CDK offers and what Pulumi offers (thinking of their "Automation API"). As the comments in this thread point out, it would open up a world of totally relevant use cases that many of us IaC users have to meet.

**Comment by mnapoli** [comment]
For clarity I don't work on the CDK, I'm just reporting a discussion that happened in an issue.

But from what I discussed with some of the CDK maintainers it seems that it's mostly about the effort and they are not ready to invest into it yet, and also that they think they would need to provide a cross-language API for all languages CDK supports (instead of just Node).

My personal wish is that they'd focus on Node only first, and start by not breaking the public API that's already available (i.e. it works already, just don't make it worse).

**Comment by AntonioAngelino** [comment]
> My personal wish is that they'd focus on Node only first, and start by not breaking the public API that's already available (i.e. it works already, just don't make it worse).

Totally agree!

**Comment by lestephane** [comment]
> I'm also curious: could you tell us something about the kinds of integration that you're thinking of?

I'm writing integration tests in Kotlin (because the project's most important parts are lambda functions written in Kotlin, in the same monorepo), while keeping the cdk definitions in typescript, and would like to deploy the infrastructure in --hotswap mode without spawning a system command, to give a better error report in the IDE's test results panel when something goes wrong.

**Comment by sladg** [comment]
Is there any progress or other tickets we can track for this feature? :)

**Comment by thdxr** [comment]
We actually are accessing CDK pro grammatically for SST.

It definitely is not what CDK intends and could probably break at any point but you can look at how we deploy stacks here:

https://github.com/serverless-stack/sst/blob/sst2/packages/sst/src/stacks/deploy.ts#L76

**Comment by mrgrain** [comment]
Thanks all for the feedback so far. We have now released a first iteration of this: [@aws-cdk/cli-lib-alpha](https://docs.aws.amazon.com/cdk/api/v2/docs/cli-lib-alpha-readme.html)

Please let me know what you're thinking and keep posting feature ideas. We are well aware this isn't a complete and ready solution yet (hence the experimental state), but it's an important stepping stone to gather interest and feedback.

**Comment by louisdussarps** [comment]
Maybe we arrive a bit late after this last AWS annoucement ; however, I permit me to show the way we programmatically manage the CDK via Orbits (an openSource flow for DevOps) - it can still be useful if you have complex interactions with your stacks or multiple deployment steps.

https://github.com/LaWebcapsule/orbits
https://github.com/LaWebcapsule/orbits/tree/main/src/examples/git-cdk-s3

**Comment by bastosvinicius** [comment]
Hello @mrgrain, I'm trying to implement this using Python 3.11, but actually facing issue related below when running synth:

```bash
cli.synth()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vinicius/.cache/pypoetry/virtualenvs/auk-I98UnL2N-py3.11/lib/python3.11/site-packages/aws_cdk/cli_lib_alpha/__init__.py", line 2276, in synth
    return typing.cast(None, jsii.ainvoke(self, "synth", [options]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinicius/.cache/pypoetry/virtualenvs/auk-I98UnL2N-py3.11/lib/python3.11/site-packages/jsii/_kernel/__init__.py", line 149, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinicius/.cache/pypoetry/virtualenvs/auk-I98UnL2N-py3.11/lib/python3.11/site-packages/jsii/_kernel/__init__.py", line 457, in ainvoke
    promise = self.provider.begin(
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/vinicius/.cache/pypoetry/virtualenvs/auk-I98UnL2N-py3.11/lib/python3.11/site-packages/jsii/_kernel/providers/process.py", line 387, in begin
    return self._process.send(request, BeginResponse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinicius/.cache/pypoetry/virtualenvs/auk-I98UnL2N-py3.11/lib/python3.11/site-packages/jsii/_kernel/providers/process.py", line 327, in send
    self._process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe```

My code is:

Running my click CLI command:

```bash
auk cloud aws instance create
```

Click method:

```bash
@aws.command('instance')
@click.pass_context
@click.argument('create', nargs=-1)
def instance(ctx, create: bool = False):
    print('create instances')
    if create:
        producer = Producer()
        cli = AwsCdkCli.from_cloud_assembly_directory_producer(producer)
        cli.synth(
            stacks=["EC2Stack"]
        )
```

aws.py file:

```bash
import os.path

from aws_cdk import Stack, App
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_iam as iam
from aws_cdk.aws_s3_assets import Asset
from constructs import Construct
from aws_cdk.cli_lib_alpha import ICloudAssemblyDirectoryProducer
import jsii

dirname = os.path.dirname(__file__)


class EC2InstanceStack(Stack):

    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        vpc = ec2.Vpc(self, "VPC",
                      nat_gateways=0,
                      subnet_configuration=[ec2.SubnetConfiguration(
                          name="public", subnet_type=ec2.SubnetType.PUBLIC)]
                      )

        amzn_linux = ec2.MachineImage.latest_amazon_linux(
            generation=ec2.AmazonLinuxGeneration.AMAZON_LINUX_2,
            edition=ec2.AmazonLinuxEdition.STANDARD,
            virtualization=ec2.AmazonLinuxVirt.HVM,
            storage=ec2.AmazonLinuxStorage.GENERAL_PURPOSE
        )

        role = iam.Role(self, "InstanceSSM",
                        assumed_by=iam.ServicePrincipal("ec2.amazonaws.com"))

        role.add_managed_policy(iam.ManagedPolicy.from_aws_managed_policy_name(
            "AmazonSSMManagedInstanceCore"))

        instance = ec2.Instance(self, "Instance",
                                instance_type=ec2.InstanceType("t3.nano"),
                                machine_image=amzn_linux,
                                vpc=vpc,
                                role=role
                                )

        # # Script in S3 as Asset
        # asset = Asset(self, "Asset", path=os.path.join(
        #     dirname, "configure.sh"))
        # local_path = instance.user_data.add_s3_download_command(
        #     bucket=asset.bucket,
        #     bucket_key=asset.s3_object_key
        # )

        # # Userdata executes script from S3
        # instance.user_data.add_execute_file_command(
        #     file_path=local_path
        # )
        # asset.grant_read(instance.role)


@jsii.implements(ICloudAssemblyDirectoryProducer)
class Producer:
    def produce(self, context):
        app = App(context=context)
        # stack = Stack(app)
        stack = EC2InstanceStack(app, "EC2Stack")
        return app.synth().directory

```

Could you explain better how can I use this?

**Comment by bastosvinicius** [comment]
Following doc: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.cli_lib_alpha/README.html

Versions:

```bash
[tool.poetry.dependencies]
python = "^3.11"
google-cloud-compute = "^1.11.0"
click = "^8.1.3"
aws-cdk-lib = "^2.82.0"
aws-cdk-cli-lib-alpha = "^2.82.0a0"
jsii = "^1.82.0"
```

**Comment by bastosvinicius** [comment]
Thanks for reply @mrgrain. Is there a forecast for definitive python support?

**Comment by mrgrain** [comment]
It's pretty much this PR: https://github.com/aws/jsii/pull/3919
I was busy with other project work, hoping to get back to it in July.

**Comment by bastosvinicius** [comment]
I'll follow the PR and wait for the new version of jsii to be released to test it. Thanks for the feedback.

**Comment by evgenyka** [comment]
Should include other CLI commands, like `cdk diff` in the scope - https://github.com/aws/aws-cdk/issues/679

**Comment by dreamorosi** [comment]
Hi, we use this package as part of our test harness to programmatically deploy infrastructure resources.

We are running into issues with Dependabot not picking up the package due to it being still in alpha, which causes issues with automatic updates for the rest of CDK libraries.

We are pursuing a fix on Dependabot side, but **we'd be interested in also understanding what's the progress on this package becoming stable** and being promoted in the main `aws-cdk-lib`/`aws-cdk`.

Is there any update that you could share?

**Comment by jiayiwang7** [comment]
> Hi, we use this package as part of our test harness to programmatically deploy infrastructure resources.
> 
> We are running into issues with Dependabot not picking up the package due to it being still in alpha, which causes issues with automatic updates for the rest of CDK libraries.
> 
> We are pursuing a fix on Dependabot side, but **we'd be interested in also understanding what's the progress on this package becoming stable** and being promoted in the main `aws-cdk-lib`/`aws-cdk`.
> 
> Is there any update that you could share?

Hi, this feature is on our roadmap. We are currently finalizing the requirements / use cases before moving to the design phase. Will provide an update once available. Thanks!

**Comment by dreamorosi** [comment]
@jiayiwang7, I'm confused, maybe I got the wrong RFC.

We are already using the `@aws-cdk/cli-lib-alfa` package which has been in alpha for the past year.

Is this the same topic? My previous message was to ask whether there were plans to promote it to stable.

**Comment by AntonioAngelino** [comment]
We've been using it for years. We bootstrapped hundreds of AWS Accounts thanks to the lib and AWS Organizations.

**Comment by mrgrain** [comment]
> @jiayiwang7, I'm confused, maybe I got the wrong RFC.
> 
> We are already using the `@aws-cdk/cli-lib-alpha` package which has been in alpha for the past year.
> 
> Is this the same topic? My previous message was to ask whether there were plans to promote it to stable.

Yes, same topic. We are looking in the missing requirements for stabilization. In it's current state, we don't consider it ready (e.g. no control over output, no return values, no useful exceptions).
We are also investigating if a standalone package makes more sense. And if so, we can likely deliver new features more incrementally under a more semver-like versioning (which I think would solve your issue with Dependabot).

**Comment by mrgrain** [comment]
> The only comment about this that I have is to ensure that when it comes to declaring aws-cdk-lib as peer dependency, ideally the ranges would be wide.

Yes, good feedback. Let's aim for `^2` as peer dependency requirement if we even need one.

**Comment by mrgrain** [comment]
We are excited to launch the **AWS CDK Toolkit Library** in **Developer Preview**. We want to hear from you and appreciate all feedback!

📜  Reference documentation: https://docs.aws.amazon.com/cdk/api/toolkit-lib/
📦  npm package: https://www.npmjs.com/package/@aws-cdk/toolkit-lib

💬 [Provide feedback, ideas and request new features](https://github.com/aws/aws-cdk-cli/discussions/154)
🐛  [Report a bug](https://github.com/aws/aws-cdk-cli/issues/new/choose)
